### PR TITLE
Translation into Spanish of the Getting Started tutorial

### PR DESCRIPTION
**Pull request by xavidp**
Hi

I provide here a translation into Spanish of the tutorial included in this package, following the structure tree [suggested by Garrick - gadenbuie - the author of the learnr package](https://github.com/rstudio/learnr/discussions/784#discussioncomment-5971629) 

I also provided a similar change proposed for the child_documents folder (I included there the 3 Rmd files, even if not changes seem to be needed in the copy_button.Rmd file)

I hope this helps for future learners of R which are non-English speakers (Spanish in this first case).

### CODE REVIEW

**Comment by davidkane9** [comment]
Hmm. This PR seems to cause some errors. Any ideas why?

**Comment by xavidp** [comment]
Something wrong about tutorial default paths?

```
  >   check_tutorial_defaults(tutorial_paths = return_tutorial_paths("tutorial.helpers"))
  Error in check_tutorial_defaults(tutorial_paths = return_tutorial_paths("tutorial.helpers")) : 
    Missing a component part from file D:/a/tutorial.helpers/tutorial.helpers/check/tutorial.helpers.Rcheck/tutorial.helpers/tutorials/getting-started_es/tutorial.Rmd
  Execution halted

1 error ✖ | 0 warnings ✔ | 0 notes ✔
```

**Comment by xavidp** [comment]
Might it be that current code in `./R/return_tutorial_paths.R` checks for Rmd files present in the package (`tutorial.helpers`), and the official package doesn't (yet) have that translated Rmd file under "getting-started_es"?

(just an educated guess, after reading and playing a bit with:
```
  x <- list.files(paste0(system.file("tutorials", package = package),
                    "/",
                    learnr::available_tutorials(package)$name), pattern = "Rmd$", full.names = TRUE)

  # Check that all the files exist. Perhaps useless since list.files() only
  # returns files which exist?

  stopifnot(all(file.exists(x)))
```

**Comment by davidkane9** [comment]
> official package doesn't (yet) have that translated Rmd file

Hmm. I don't think that that can be the cause. After all, the package passes checks even on systems, like CRAN and Github, which do not have the official tutorial.helpers package installed at all.

But, if you don't think that return_tutorial_paths() is doing what it claims to be doing (or what it should be doing), please speak up!

**Comment by davidkane9** [comment]
Note that one error derives from check_tutorial_defaults(), which right now hardcodes the child document strings in a hacky fashion. We could generalize this at a later date. But let's get a simpler PR working first.

**Comment by xavidp** [comment]
Ok, can you try again now? (I nuked the Rmd files under child_documents_es, and the references to them, for the time being, to keep the PR simpler)

**Pull request merged**
